### ISSUE TITLE
再提一个好毛

### ISSUE THREAD

**Issue by jaychoubaby** [745240/ibuick#1]
大佬 巴奴毛肚小程序的毛真的很不错，签到领积分，积分可以兑换手动工艺品实物，都是很实用的物件，我尝试过自己写脚本，但是他的接口有验签，不会逆向所以放弃了
![IMG_1988](https://github.com/745240/ibuick/assets/26641387/8363784a-3272-466e-8bf3-7523e8de374c)

**Comment by 745240** [comment]
小程序的逆向我没接触过，这个还是找下leaf大佬吧，ibuick这个没有车的跑了也没用，所以只能自力更生了

**Comment by jaychoubaby** [comment]
> 小程序的逆向我没接触过，这个还是找下leaf大佬吧，ibuick这个没有车的跑了也没用，所以只能自力更生了

这个小程序是接口要加签，所以没弄出来，我刚好是别克车，以前还挺容易后面改版了一次不好搞了
