### ISSUE TITLE
connect ETIMEDOUT 210.75.88.12:443 undefined

### ISSUE THREAD

**Issue by jaychoubaby** [745240/ibuick#2]
## 开始执行... 2023-06-29 13:48:55

🔔别克汇, 开始!
一键任务
connect ETIMEDOUT 210.75.88.12:443 undefined

 忘记了 失败了!请稍后尝试!!

❗️别克汇, 错误!
TypeError: Cannot read properties of undefined (reading 'message')
    at signIn (/ql/scripts/back/ibuick.js:15:6314)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (/ql/scripts/back/ibuick.js:15:3408)
    at async /ql/scripts/back/ibuick.js:15:2692

🔔别克汇, 结束! 🕛 129.768 秒

## 执行结束... 2023-06-29 13:51:07 耗时 132 秒

如果有联系方式我愿意提供token帮助调试

**Comment by jaychoubaby** [comment]
我发现这个错误的原因是我的服务器ping 不通 210.75.88.12，我本地是可以ping通

**Comment by jaychoubaby** [comment]
我用的是甲骨文服务器跑的青龙，估计是他们把禁了国外ip，既然每天都要手动抓token，大佬能不能转换一下脚本编程qx脚本在手机跑啊，手机可以自动抓cookie，也方便很多，青龙还得去同步变量

**Comment by jaychoubaby** [comment]
折腾了半天上了青龙代理，结果还是不行，心态崩了

## 开始执行... 2023-06-29 16:49:21


🔔别克汇, 开始!
一键任务
Client network socket disconnected before secure TLS connection was established undefined

 忘记了 失败了!请稍后尝试!!

❗️别克汇, 错误!
TypeError: Cannot read properties of undefined (reading 'message')
    at signIn (/ql/scripts/back/ibuick.js:23:6314)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (/ql/scripts/back/ibuick.js:23:3408)
    at async /ql/scripts/back/ibuick.js:23:2692

🔔别克汇, 结束! 🕛 6.005 秒


## 执行结束... 2023-06-29 16:49:29 耗时 8 秒

**Comment by 745240** [comment]
> 折腾了半天上了青龙代理，结果还是不行，心态崩了
> 
> ## 开始执行... 2023-06-29 16:49:21
> 🔔别克汇, 开始! 一键任务 Client network socket disconnected before secure TLS connection was established undefined
> 
> 忘记了 失败了!请稍后尝试!!
> 
> ❗️别克汇, 错误! TypeError: Cannot read properties of undefined (reading 'message') at signIn (/ql/scripts/back/ibuick.js:23:6314) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async start (/ql/scripts/back/ibuick.js:23:3408) at async /ql/scripts/back/ibuick.js:23:2692
> 
> 🔔别克汇, 结束! 🕛 6.005 秒
> 
> ## 执行结束... 2023-06-29 16:49:29 耗时 8 秒

你这个代理好像不太行，确实是你国外ip的缘故没办法请求，那个ip是别克的

**Comment by jaychoubaby** [comment]
能不能求一下源码，我想改造一下在手机上用qx跑，抓cookie也方便

**Comment by 745240** [comment]
没必要源码，你抓包会的，其实可以你自己抓下就能找的了，v3和v2的，只有记账和发动态不一样，不需要解密data的，直接可以使用

**Comment by jaychoubaby** [comment]
> 

好  那只能手撸了 懒得折腾青龙代理了

**Comment by jaychoubaby** [comment]
> 没必要源码，你抓包会的，其实可以你自己抓下就能找的了，v3和v2的，只有记账和发动态不一样，不需要解密data的，直接可以使用

请问v3 v2这两个方法会一直穿插调用，他的调用逻辑是什么样的，有点看不懂

**Comment by jaychoubaby** [comment]
我的理解是不是每执行完一个任务之后就需要调用一次v3 或者 v2？

**Comment by 745240** [comment]
> 我的理解是不是每执行完一个任务之后就需要调用一次v3 或者 v2？

每次完成一个任务会请求一个v3

**Comment by jaychoubaby** [comment]
> > 我的理解是不是每执行完一个任务之后就需要调用一次v3 或者 v2？
> 
> 每次完成一个任务会请求一个v3

请问公里数那个任务逻辑要怎么破，添加一个公里数之后再重放会提示公里数已经添加过了，但是请求数据又是加密的，无法自己变化，想着添加之后再删除，由于数据加密了也行不通，删除会提示找不到数据

**Comment by 745240** [comment]
> > > 我的理解是不是每执行完一个任务之后就需要调用一次v3 或者 v2？
> > 
> > 
> > 每次完成一个任务会请求一个v3
> 
> 请问公里数那个任务逻辑要怎么破，添加一个公里数之后再重放会提示公里数已经添加过了，但是请求数据又是加密的，无法自己变化，想着添加之后再删除，由于数据加密了也行不通，删除会提示找不到数据

不解密没办法，只有手动删，每次记录后生成的值是不一样的，尽管距离一样

**Comment by jaychoubaby** [comment]
> > > > 我的理解是不是每执行完一个任务之后就需要调用一次v3 或者 v2？
> > > 
> > > 
> > > 每次完成一个任务会请求一个v3
> > 
> > 
> > 请问公里数那个任务逻辑要怎么破，添加一个公里数之后再重放会提示公里数已经添加过了，但是请求数据又是加密的，无法自己变化，想着添加之后再删除，由于数据加密了也行不通，删除会提示找不到数据
> 
> 不解密没办法，只有手动删，每次记录后生成的值是不一样的，尽管距离一样

v3的方法都已经没问题了，添加评论 回答 点赞 这几个一直有问题，提示“操作频繁，请稍后再试”，不知道什么原因，抓包工具里面重复请求都是成功的，另外我发现v2方法好像没什么用
